# common.yml
name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  job_template:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This common2"
      - name: Step 2
        run: echo "This common2"
