name: java SDK

on:
  pull_request:
    branches:
      - master
  
  workflow_dispatch:
    inputs:
      sdkVersion:
        description: 'SDK version'
        required: false
        type: string
      sdkVersionType:
        description: 'SDK version type'
        required: false
        type: choice
        options:
          - internal
          - public

jobs:
  build:
    name: run-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: print trigger details
        run: |
          echo ${{ github.event.client_payload.github.action }}
          echo ${{ github.event.client_payload.github.actor }}
      - name: echo "Hello T"
        run: echo "Hello respository dispatch test"
