name: java SDK

on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:

jobs:
  build:
    name: run-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: print trigger details
        run: |
          echo ${{ github.event.client_payload.github.action }}
          echo ${{ github.event.client_payload.github.actor }}
      - name: echo "Hello"
        run: echo "Hello respository dispatch"
