name: Python SDK

on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
    inputs:
      sdkVersion:
        description: 'Sdk version'
        required: false
        type: string
      typeOfSdkVersion:
        description: 'Type of SDK version'
        required: false
        type: choice
        options:
          - internal
          - external
      

jobs:
  build:
    name: run-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: print trigger details
        run: |
          echo ${{ github.event.client_payload.github.action }}
          echo ${{ github.event.client_payload.typeOfSdkVersion }}
      - name: echo "Hello"
        run: echo "Hello test2yml"
